web/router.ex
defmodule SopostPeople.Router do
  use SopostPeople.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SopostPeople do
    pipe_through :browser # Use the default browser stack

    get "/", PeopleController, :index
    get "/:location", PeopleController, :show
    get "/people/new", PeopleController, :new
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", SopostPeople do
    pipe_through :api

    resources "/people", PeopleController, only: [:create]
  end
end

lib/sopost_people/endpoint.ex
defmodule SopostPeople.Endpoint do
  use Phoenix.Endpoint, otp_app: :sopost_people

  socket "/socket", SopostPeople.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :sopost_people, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_sopost_people_key",
    signing_salt: "I8IKpdGP"

  plug SopostPeople.Router
end

lib/sopost_people/repo.ex
defmodule SopostPeople.Repo do
  use Ecto.Repo, otp_app: :sopost_people

  def get_by_location(module, location) do
    Enum.filter all(module), fn p -> String.contains?(p.locations, location) end
  end
end

web/models/person.ex
defmodule SopostPeople.Person do
  use SopostPeople.Web, :model

  schema "people" do
    field :name, :string
    field :title, :string
    field :locations, :string
    field :avatar, :string

    timestamps
  end

  def changeset(model, params \\ :empty) do
    model
      |> cast(params, ~w(name title locations avatar), [])
  end
end

web/controllers/page_controller.ex
defmodule SopostPeople.PageController do
  use SopostPeople.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/people_controller.ex
defmodule SopostPeople.PeopleController do
  use SopostPeople.Web, :controller

  alias SopostPeople.Person

  def index(conn, _params) do
    people = Repo.all(SopostPeople.Person)
    render conn, "index.html", people: people
  end

  def show(conn, %{"location" => location}) do
    people = Repo.get_by_location(SopostPeople.Person, location)
    render conn, "show.html", people: people
  end

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, params) do
    changeset = Person.changeset(%Person{}, params)

    case Repo.insert(changeset) do
      {:ok, person} ->
        render conn, "person.json", person: person
      {:error, changeset} ->
        conn
    end
  end
end

web/views/error_view.ex
defmodule SopostPeople.ErrorView do
  use SopostPeople.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule SopostPeople.LayoutView do
  use SopostPeople.Web, :view
end

web/views/page_view.ex
defmodule SopostPeople.PageView do
  use SopostPeople.Web, :view
end

web/views/people_view.ex
defmodule SopostPeople.PeopleView do
  use SopostPeople.Web, :view

  def split_locations(locations) do
    locations
      |> String.split(",")
  end

  def render("person.json", %{person: person}) do
    %{
      name: person.name,
      title: person.title,
      locations: person.locations,
      avatar: person.avatar
    }
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sopost People</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/main.css") %>">
  </head>

  <body>
    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>
  </body>
</html>

web/templates/people/index.html.eex
<h1>People</h1>
<table>
  <%= for person <- @people do %>
    <tr>
      <td><img src="<%= person.avatar %>"/></td>
      <td><%= person.name %></td>
      <td><%= person.title %></td>
      <td>
        <%= for loc <- split_locations(person.locations) do %>
          <%= link loc, to: people_path(@conn, :show, loc) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

web/templates/people/location.html.eex
<h1>People</h1>
<table>
  <%= for person <- @people do %>
    <tr>
      <td><img src="<%= person.avatar %>"/></td>
      <td><%= person.name %></td>
      <td><%= person.title %></td>
      <td>
        <%= for loc <- person.locations do %>
          <%= link loc, to: people_path(@conn, :show, loc) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

web/templates/people/new.html.eex
<div id="elm-main"></div>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>

web/templates/people/show.html.eex
<h1>People</h1>
<table>
  <%= for person <- @people do %>
    <tr>
      <td><img src="<%= person.avatar %>"/></td>
      <td><%= person.name %></td>
      <td><%= person.title %></td>
      <td>
        <%= for loc <- split_locations(person.locations) do %>
          <%= link loc, to: people_path(@conn, :show, loc) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>